language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.5
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.6
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6 COVERAGE=1 FUNCTIONAL=0
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Installs TYPO3
  - composer require --dev typo3/cms=$TYPO3_VERSION;
  # Restore composer.json
  - git checkout composer.json;
  - export TYPO3_PATH_WEB=$PWD/.Build/Web;
  - export UNIT_XML=".Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml"
  - export FUNCTIONAL_XML=".Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml"

script:
  # Execute unit tests
  - >
    echo "Running unit tests";
    if [[ "$COVERAGE" == "1" ]]; then
      .Build/bin/phpunit --whitelist Classes/ --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit

      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    else
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi

  # Execute functional tests, if enabled
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo "Running functional tests"
      export typo3DatabaseHost="localhost";
      export typo3DatabaseName="typo3";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      .Build/bin/phpunit --colors -c $FUNCTIONAL_XML Tests/Functional/
    fi

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
